# https://docs.python.org/3/library/logging.config.html#logging-config-dictschema

version: 1

disable_existing_loggers: True

formatters:
  standard:
    format: '>> %(levelname)s -- %(asctime)s -- %(name)s -- %(pathname)s -- %(funcName)s:%(lineno)d -- %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
    
root:
  formatter: standard
  level: INFO
  handlers:
    - console
    - info
    - error
    - tmp

handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: standard
    level: INFO
  info:
    class: logging.handlers.RotatingFileHandler
    filename: {{ info_logger() }}
    maxBytes: 500000
    backupCount: 3
    encoding: utf-8
    formatter: standard
    level: INFO
  error:
    class: logging.handlers.RotatingFileHandler
    filename: {{ error_logger() }}
    level: WARNING
    maxBytes: 500000
    backupCount: 3
    encoding: utf-8
    formatter: standard
  tmp:
    class: logging.FileHandler
    filename: {{ tmp_logger() }}
    mode: a
    encoding: utf-8
    formatter: standard
    level: INFO